services:
  - type: web
    name: chattybot-grammar-correction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python grammar_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # set this in Render's dashboard
